---
deployment:
  tasks:
    - export DEPLOYPATH=/home/parro178/repositories/zeusmarmoleria
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
  